# Generated by Django 5.2.3 on 2025-06-26 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="projects.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
